-- Noleggiatore
INSERT INTO Units
		(Type,							Class,	PrereqTech,	Combat,	Cost,	Moves,	HurryCostModifier,	CombatClass,	Domain,	DefaultUnitAI,	Description,							Civilopedia,									Strategy,											Help,											MilitarySupport,	MilitaryProduction,	Pillage,	Mechanized,	ObsoleteTech,	AdvancedStartCost,	MinAreaSize,	UnitArtInfo,	UnitFlagIconOffset,	IconAtlas,	PortraitIndex,	MoveRate)
SELECT	'UNIT_C15_VENICE_NOLEGGIATORE',	Class,	PrereqTech,	Combat,	Cost,	Moves,	HurryCostModifier,	CombatClass,	Domain,	DefaultUnitAI,	'TXT_KEY_UNIT_C15_VENICE_NOLEGGIATORE',	'TXT_KEY_UNIT_C15_VENICE_NOLEGGIATORE_PEDIA',	'TXT_KEY_UNIT_C15_VENICE_NOLEGGIATORE_STRATEGY',	'TXT_KEY_UNIT_C15_VENICE_NOLEGGIATORE_HELP',	MilitarySupport,	MilitaryProduction,	Pillage,	Mechanized,	ObsoleteTech,	AdvancedStartCost,	MinAreaSize,	UnitArtInfo,	UnitFlagIconOffset,	IconAtlas,	PortraitIndex,	MoveRate
FROM Units WHERE Type = 'UNIT_CARAVEL';

INSERT INTO Unit_AITypes
		(UnitType,						UnitAIType)
SELECT	'UNIT_C15_VENICE_NOLEGGIATORE',	UnitAIType
FROM Unit_AITypes WHERE UnitType = 'UNIT_CARAVEL';

INSERT INTO Unit_ClassUpgrades
		(UnitType,						UnitClassType)
SELECT	'UNIT_C15_VENICE_NOLEGGIATORE',	UnitClassType
FROM Unit_ClassUpgrades WHERE UnitType = 'UNIT_CARAVEL';

INSERT INTO Unit_Flavors
		(UnitType,						FlavorType,	Flavor)
SELECT	'UNIT_C15_VENICE_NOLEGGIATORE',	FlavorType,	Flavor
FROM Unit_Flavors WHERE UnitType = 'UNIT_CARAVEL';

INSERT INTO Unit_FreePromotions
		(UnitType,						PromotionType)
SELECT	'UNIT_C15_VENICE_NOLEGGIATORE',	PromotionType
FROM Unit_FreePromotions WHERE UnitType = 'UNIT_CARAVEL';

INSERT INTO UnitGameplay2DScripts
		(UnitType,						SelectionSound,	FirstSelectionSound)
SELECT	'UNIT_C15_VENICE_NOLEGGIATORE',	SelectionSound,	FirstSelectionSound
FROM UnitGameplay2DScripts WHERE UnitType = 'UNIT_CARAVEL';

INSERT INTO UnitPromotions
		(Type,										Description,										Help,													PediaType,			PediaEntry,											CannotBeChosen,	VisibilityChange,	MovesChange,	IconAtlas,			PortraitIndex)
VALUES	('PROMOTION_C15_VENICE_NOLEGGIATORE',		'TXT_KEY_PROMOTION_C15_VENICE_NOLEGGIATORE',		'TXT_KEY_PROMOTION_C15_VENICE_NOLEGGIATORE_HELP',		'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_C15_VENICE_NOLEGGIATORE',		1,				0,					0,				'ABILITY_ATLAS',	59),
		('PROMOTION_C15_VENICE_NOLEGGIATORE_ROUTE',	'TXT_KEY_PROMOTION_C15_VENICE_NOLEGGIATORE_ROUTE',	'TXT_KEY_PROMOTION_C15_VENICE_NOLEGGIATORE_HELP_ROUTE',	'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_C15_VENICE_NOLEGGIATORE_ROUTE',	1,				1,					0,				'ABILITY_ATLAS',	58);
		
INSERT INTO Unit_FreePromotions
		(UnitType,							PromotionType)
VALUES	('UNIT_C15_VENICE_NOLEGGIATORE',	'PROMOTION_C15_VENICE_NOLEGGIATORE');

UPDATE Units
SET PrereqTech = (SELECT PrereqTech FROM Units WHERE Type = 'UNIT_EE_CARRACK'), Combat = (SELECT Combat FROM Units WHERE Type = 'UNIT_EE_CARRACK'), Cost = (SELECT Cost FROM Units WHERE Type = 'UNIT_EE_CARRACK'), Moves = (SELECT Moves FROM Units WHERE Type = 'UNIT_EE_CARRACK'), HurryCostModifier = (SELECT HurryCostModifier FROM Units WHERE Type = 'UNIT_EE_CARRACK'), Help = 'TXT_KEY_UNIT_C15_VENICE_NOLEGGIATORE_HELP_EE', Strategy = 'TXT_KEY_UNIT_C15_VENICE_NOLEGGIATORE_STRATEGY_EE', ObsoleteTech = (SELECT ObsoleteTech FROM Units WHERE Type = 'UNIT_EE_CARRACK'), UnitArtInfo = (SELECT UnitArtInfo FROM Units WHERE Type = 'UNIT_EE_CARRACK'), AdvancedStartCost = (SELECT AdvancedStartCost FROM Units WHERE Type = 'UNIT_EE_CARRACK'), CombatClass = (SELECT CombatClass FROM Units WHERE Type = 'UNIT_EE_CARRACK'), Class = (SELECT Class FROM Units WHERE Type = 'UNIT_EE_CARRACK')
WHERE Type = 'UNIT_C15_VENICE_NOLEGGIATORE'
AND EXISTS (SELECT * FROM Units WHERE Type = 'UNIT_EE_CARRACK');

UPDATE Unit_ClassUpgrades
SET UnitClassType = (SELECT UnitClassType FROM Unit_ClassUpgrades WHERE UnitType = 'UNIT_EE_CARRACK')
WHERE UnitType = 'UNIT_C15_VENICE_NOLEGGIATORE'
AND EXISTS (SELECT * FROM Units WHERE Type = 'UNIT_EE_CARRACK');

DELETE FROM Unit_Flavors WHERE UnitType = 'UNIT_C15_VENICE_NOLEGGIATORE' AND EXISTS (SELECT * FROM Units WHERE Type = 'UNIT_EE_CARRACK');

INSERT INTO Unit_Flavors
		(UnitType,						FlavorType,	Flavor)
SELECT	'UNIT_C15_VENICE_NOLEGGIATORE',	FlavorType,	Flavor
FROM Unit_Flavors WHERE UnitType = 'UNIT_EE_CARRACK'
AND EXISTS (SELECT * FROM Units WHERE Type = 'UNIT_EE_CARRACK');

DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_C15_VENICE_NOLEGGIATORE' AND PromotionType != 'PROMOTION_C15_VENICE_NOLEGGIATORE' AND EXISTS (SELECT * FROM Units WHERE Type = 'UNIT_EE_CARRACK');

INSERT INTO Unit_FreePromotions
		(UnitType,						PromotionType)
SELECT	'UNIT_C15_VENICE_NOLEGGIATORE',	PromotionType
FROM Unit_FreePromotions WHERE UnitType = 'UNIT_EE_CARRACK'
AND EXISTS (SELECT * FROM Units WHERE Type = 'UNIT_EE_CARRACK');

-- Great Galleas

INSERT INTO UnitPromotions
		(Type,										Description,										Help,													PediaType,			PediaEntry,											CannotBeChosen,	IconAtlas,			PortraitIndex,	LostWithUpgrade,	CityAttack)
VALUES	('PROMOTION_C15_VENICE_GREAT_CITY_BONUS',	'TXT_KEY_PROMOTION_C15_VENICE_GREAT_CITY_BONUS',	'TXT_KEY_PROMOTION_C15_VENICE_GREAT_CITY_BONUS_HELP',	'PEDIA_ATTRIBUTES',	'TXT_KEY_PROMOTION_C15_VENICE_GREAT_CITY_BONUS',	1,				'PROMOTION_ATLAS',	40,				1,					100);

UPDATE Units
SET Help = 'TXT_KEY_UNIT_C15_VENETIAN_GALLEASS_HELP', Strategy = 'TXT_KEY_UNIT_C15_VENETIAN_GALLEASS_STRATEGY'
WHERE Type = 'UNIT_VENETIAN_GALLEASS';

INSERT INTO Unit_FreePromotions
		(UnitType,					PromotionType)
VALUES	('UNIT_VENETIAN_GALLEASS',	'PROMOTION_C15_VENICE_GREAT_CITY_BONUS'),
		('UNIT_VENETIAN_GALLEASS',	'PROMOTION_MUST_SET_UP');

-- UA

INSERT INTO BuildingClasses
		(Type,									DefaultBuilding,					Description)
VALUES	('BUILDINGCLASS_C15_VENICE_TRADE_SLOT',	'BUILDING_C15_VENICE_TRADE_SLOT',	'TXT_KEY_BUILDING_C15_VENICE_TRADE_SLOT'),
		('BUILDINGCLASS_C15_VENICE_NAVAL_PROD',	'BUILDING_C15_VENICE_NAVAL_PROD',	'TXT_KEY_BUILDING_C15_VENICE_NAVAL_PROD'),
		('BUILDINGCLASS_C15_VENICE_CAP_CAPPED',	'BUILDING_C15_VENICE_CAP_CAPPED',	'TXT_KEY_BUILDING_C15_VENICE_CAP_CAPPED');
		
INSERT INTO Buildings		
		(Type,								BuildingClass,								Description,								Cost,	FaithCost,	GreatWorkCount,		PrereqTech,		NeverCapture,	NukeImmune,		PortraitIndex,	IconAtlas,		NumTradeRouteBonus)
VALUES	('BUILDING_C15_VENICE_TRADE_SLOT',	'BUILDINGCLASS_C15_VENICE_TRADE_SLOT',		'TXT_KEY_BUILDING_C15_VENICE_TRADE_SLOT',	-1,		-1,			-1,					NULL,			1,				1,				17,				'BW_ATLAS_1',	1),
		('BUILDING_C15_VENICE_NAVAL_PROD',	'BUILDINGCLASS_C15_VENICE_NAVAL_PROD',		'TXT_KEY_BUILDING_C15_VENICE_NAVAL_PROD',	-1,		-1,			-1,					NULL,			1,				1,				17,				'BW_ATLAS_1',	0),
		('BUILDING_C15_VENICE_CAP_CAPPED',	'BUILDINGCLASS_C15_VENICE_CAP_CAPPED',		'TXT_KEY_BUILDING_C15_VENICE_CAP_CAPPED',	-1,		-1,			-1,					NULL,			0,				1,				19,				'BW_ATLAS_1',	0);

UPDATE Buildings SET ConquestProb = 100 WHERE Type = 'BUILDING_C15_VENICE_CAP_CAPPED';
		
INSERT INTO Building_DomainProductionModifiers
		(BuildingType,						DomainType,		Modifier)
VALUES	('BUILDING_C15_VENICE_NAVAL_PROD',	'DOMAIN_SEA',	3);

INSERT INTO Traits
		(Type,							ShortDescription,					Description)
VALUES	('TRAIT_C15_VENICE_CRUSADE',	'TXT_KEY_TRAIT_C15_VENICE_CRUSADE',	'TXT_KEY_TRAIT_C15_VENICE_CRUSADE_DESC');

-- Switching

DELETE FROM Civilization_UnitClassOverrides WHERE UnitType = 'UNIT_VENETIAN_MERCHANT';

INSERT INTO Civilization_UnitClassOverrides
		(CivilizationType,		UnitClassType,			UnitType)
VALUES	('CIVILIZATION_VENICE',	'UNITCLASS_CARAVEL',	'UNIT_C15_VENICE_NOLEGGIATORE');

UPDATE Civilization_UnitClassOverrides SET UnitClassType = 'UNITCLASS_EE_CARRACK' WHERE UnitType = 'UNIT_C15_VENICE_NOLEGGIATORE' AND EXISTS (SELECT * FROM Units WHERE Type = 'UNIT_EE_CARRACK');

UPDATE Leader_Traits SET TraitType = 'TRAIT_C15_VENICE_CRUSADE' WHERE LeaderType = 'LEADER_ENRICO_DANDOLO';

-- Thanks JiffJiff

INSERT INTO Civilization_CityNames 
			(CivilizationType, 			CityName)
VALUES		('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_VERONA'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_VICENZA'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_PARENZO'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_ZARA'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_SPALATO'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_DURAZZO'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_CHANIA'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_PATRAS'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_CANDIA'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_NEGROPONTE'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_AQUILEA'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_POLA'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_NICOISA'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_BRESCIA'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_PADUA'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_BERGAMO'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_MYSTRAS'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_LIMASSOL'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_CHIOGGIA'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_MIRA'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_MIRANO'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_CASTELNUOVO'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_ERACLEA'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_MODON'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_FAMAGUSTA'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_LEPANTO'),
			('CIVILIZATION_VENICE', 	'TXT_KEY_CITY_NAME_JFD_ANTIVARI');
			
-- AI

UPDATE Leaders SET Boldness = 6, MinorCivCompetitiveness = 4 WHERE Type = 'LEADER_ENRICO_DANDOLO';

UPDATE Leader_MajorCivApproachBiases SET Bias = 6 WHERE MajorCivApproachType = 'MAJOR_CIV_APPROACH_WAR' AND LeaderType = 'LEADER_ENRICO_DANDOLO';

UPDATE Leader_Flavors SET Flavor = 7 WHERE FlavorType = 'FLAVOR_OFFENSE' AND LeaderType = 'LEADER_ENRICO_DANDOLO';

UPDATE Leader_Flavors SET Flavor = 8 WHERE FlavorType = 'FLAVOR_NAVAL' AND LeaderType = 'LEADER_ENRICO_DANDOLO';

UPDATE Leader_Flavors SET Flavor = 8 WHERE FlavorType = 'FLAVOR_WATER_CONNECTION' AND LeaderType = 'LEADER_ENRICO_DANDOLO';

UPDATE Leader_Flavors SET Flavor = 9 WHERE FlavorType = 'FLAVOR_I_SEA_TRADE_ROUTE' AND LeaderType = 'LEADER_ENRICO_DANDOLO';



