UPDATE Civilizations
SET Description = 'TXT_KEY_ER_T_BAGAN', ShortDescription = 'TXT_KEY_ER_T_BAGAN_SHORT', Adjective = 'TXT_KEY_ER_T_BAGAN_ADJ'
WHERE Type = 'CIVILIZATION_BURMA';

UPDATE Buildings
SET Help = 'TXT_KEY_ER_T_BUILDING_PAYA_HELP', Strategy = 'TXT_KEY_ER_T_BUILDING_PAYA_STRATEGY'
WHERE Type = 'BUILDING_PAYA';

UPDATE Units
SET Help = 'TXT_KEY_ER_T_UNIT_KYUNDAW_HELP', Strategy = 'TXT_KEY_ER_T_UNIT_KYUNDAW_STRATEGY'
WHERE Type = 'UNIT_BURMESE_KYUNDAW_CONSCRIPT';

UPDATE Traits
SET Description = 'TXT_KEY_TRAIT_ER_T_YAMA_ZATDAW'
WHERE Type = 'TRAIT_YAMA_ZATDAW';


DELETE FROM Civilization_CityNames 
WHERE CivilizationType = 'CIVILIZATION_BURMA';

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_BAGAN'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_MINBU'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_KYAUKSE'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_TAGAUNG'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_THATON'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_BHAMO'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_THIRI_PYITSAYA'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_PYAYMYO'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_NYAUNG_OO'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_MYINSAING'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_MOGAUNG'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_MOTTAMA'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_LEYA'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_TAUNGBI'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_BAGO'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_MYINKABA'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_PATHEIN'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_PYINSA'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_PWASAW'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_HANLIN'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_POPA'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_MONE'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_DALA'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_SALIN'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');

INSERT INTO Civilization_CityNames
		(CivilizationType, 			CityName)
SELECT	'CIVILIZATION_BURMA', 		'TXT_KEY_CITY_NAME_ER_BAGAN_T_LAUNGYET'
WHERE EXISTS (SELECT Type FROM Civilizations WHERE Type = 'CIVILIZATION_BURMA');