UPDATE Resources SET PolicyReveal = 
	( CASE WHEN EXISTS(SELECT Type FROM Buildings WHERE Type = 'BUILDING_DECISIONS_ROMANCONCRETE' )
		THEN 'POLICY_EXPLORATION_FINISHER_DUMMY'
		ELSE 'POLICY_EXPLORATION_FINISHER' END 
	) WHERE Type = 'RESOURCE_HIDDEN_ARTIFACTS';

CREATE TRIGGER ExplorationFinisherDummy
AFTER INSERT ON Buildings WHEN 'BUILDING_DECISIONS_ROMANCONCRETE' = NEW.Type
BEGIN

	UPDATE Resources
	SET PolicyReveal = 'POLICY_EXPLORATION_FINISHER_DUMMY'
	WHERE Type = 'RESOURCE_HIDDEN_ARTIFACTS';

END;