UPDATE Civilization_Religions SET ReligionType = 
	( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type="RELIGION_FORN_SIDR" )
		THEN "RELIGION_BUDDHISM"
		ELSE "RELIGION_BUDDHISM" END
	) WHERE CivilizationType = "CIVILIZATION_TAUNGOO";

CREATE TRIGGER ReligionERTaungooTest
AFTER INSERT ON Religions WHEN 'RELIGION_BUDDHISM' = NEW.Type
BEGIN
	UPDATE Civilization_Religions 
	SET ReligionType = 'RELIGION_BUDDHISM'
	WHERE CivilizationType IN ('CIVILIZATION_TAUNGOO');
END;