--==========================================================================================================================	
-- IMPROVEMENTS
--==========================================================================================================================	
-- Improvements
------------------------------
INSERT INTO Improvements
			(Type,								Description,							Civilopedia,												ArtDefineTag,											RequiresFlatlands,		GraphicalOnly,		PillageGold,		PortraitIndex,	IconAtlas)
VALUES		('IMPROVEMENT_MC_ROYAL_PYRAMID2',	'TXT_KEY_MC_LITE_NUBIAN_ROYAL_PYRAMID',	'TXT_KEY_CIVILOPEDIA_MC_LITE_NUBIAN_ROYAL_PYRAMID_TEXT',	'ART_DEF_IMPROVEMENT_MC_LITE_NUBIAN_ROYAL_PYRAMID', 	1,						1,					40,					3,				'MC_LITE_NUBIA_ATLAS'),
			('IMPROVEMENT_MC_ROYAL_PYRAMID3',	'TXT_KEY_MC_LITE_NUBIAN_ROYAL_PYRAMID',	'TXT_KEY_CIVILOPEDIA_MC_LITE_NUBIAN_ROYAL_PYRAMID_TEXT',	'ART_DEF_IMPROVEMENT_MC_LITE_NUBIAN_ROYAL_PYRAMID', 	1,						1,					40,					3,				'MC_LITE_NUBIA_ATLAS'),
			('IMPROVEMENT_MC_ROYAL_PYRAMID4',	'TXT_KEY_MC_LITE_NUBIAN_ROYAL_PYRAMID',	'TXT_KEY_CIVILOPEDIA_MC_LITE_NUBIAN_ROYAL_PYRAMID_TEXT',	'ART_DEF_IMPROVEMENT_MC_LITE_NUBIAN_ROYAL_PYRAMID', 	1,						1,					40,					3,				'MC_LITE_NUBIA_ATLAS'),
			('IMPROVEMENT_MC_ROYAL_PYRAMID5',	'TXT_KEY_MC_LITE_NUBIAN_ROYAL_PYRAMID',	'TXT_KEY_CIVILOPEDIA_MC_LITE_NUBIAN_ROYAL_PYRAMID_TEXT',	'ART_DEF_IMPROVEMENT_MC_LITE_NUBIAN_ROYAL_PYRAMID', 	1,						1,					40,					3,				'MC_LITE_NUBIA_ATLAS'),
			('IMPROVEMENT_MC_ROYAL_PYRAMID6',	'TXT_KEY_MC_LITE_NUBIAN_ROYAL_PYRAMID',	'TXT_KEY_CIVILOPEDIA_MC_LITE_NUBIAN_ROYAL_PYRAMID_TEXT',	'ART_DEF_IMPROVEMENT_MC_LITE_NUBIAN_ROYAL_PYRAMID', 	1,						1,					40,					3,				'MC_LITE_NUBIA_ATLAS'),
			('IMPROVEMENT_MC_ROYAL_PYRAMID7',	'TXT_KEY_MC_LITE_NUBIAN_ROYAL_PYRAMID',	'TXT_KEY_CIVILOPEDIA_MC_LITE_NUBIAN_ROYAL_PYRAMID_TEXT',	'ART_DEF_IMPROVEMENT_MC_LITE_NUBIAN_ROYAL_PYRAMID', 	1,						1,					40,					3,				'MC_LITE_NUBIA_ATLAS'),
			('IMPROVEMENT_MC_ROYAL_PYRAMID8',	'TXT_KEY_MC_LITE_NUBIAN_ROYAL_PYRAMID',	'TXT_KEY_CIVILOPEDIA_MC_LITE_NUBIAN_ROYAL_PYRAMID_TEXT',	'ART_DEF_IMPROVEMENT_MC_LITE_NUBIAN_ROYAL_PYRAMID', 	1,						1,					40,					3,				'MC_LITE_NUBIA_ATLAS');
------------------------------
-- Improvement_Yields
------------------------------
INSERT INTO Improvement_Yields
			(ImprovementType,					YieldType,			Yield)
VALUES		('IMPROVEMENT_MC_ROYAL_PYRAMID2',	'YIELD_CULTURE',	1),
			('IMPROVEMENT_MC_ROYAL_PYRAMID3',	'YIELD_CULTURE',	2),
			('IMPROVEMENT_MC_ROYAL_PYRAMID4',	'YIELD_CULTURE',	2),
			('IMPROVEMENT_MC_ROYAL_PYRAMID5',	'YIELD_CULTURE',	3),
			('IMPROVEMENT_MC_ROYAL_PYRAMID6',	'YIELD_CULTURE',	3),
			('IMPROVEMENT_MC_ROYAL_PYRAMID7',	'YIELD_CULTURE',	4),
			('IMPROVEMENT_MC_ROYAL_PYRAMID8',	'YIELD_CULTURE',	4),
			('IMPROVEMENT_MC_ROYAL_PYRAMID2',	'YIELD_FAITH',		1),
			('IMPROVEMENT_MC_ROYAL_PYRAMID3',	'YIELD_FAITH',		1),
			('IMPROVEMENT_MC_ROYAL_PYRAMID4',	'YIELD_FAITH',		1),
			('IMPROVEMENT_MC_ROYAL_PYRAMID5',	'YIELD_FAITH',		1),
			('IMPROVEMENT_MC_ROYAL_PYRAMID6',	'YIELD_FAITH',		1),
			('IMPROVEMENT_MC_ROYAL_PYRAMID7',	'YIELD_FAITH',		1),
			('IMPROVEMENT_MC_ROYAL_PYRAMID8',	'YIELD_FAITH',		1),;
