--Blank Policies


INSERT INTO Policies 
		(Type,												 Description,								          Civilopedia,                                       Help,	 	    GridX,	GridY,	PortraitIndex,		     IconAtlas,		   IconAtlasAchieved)
VALUES	('POLICY_SHANG_BLANK',	        'TXT_KEY_POLICY_DYNASTY_BLANK_1',			    'TXT_KEY_POLICY_DYNASTY_BLANK_TEXT_1',	    'TXT_KEY_POLICY_DYNASTY_BLANK_HELP_1',			 1000,	 1000,		       47,		'POLICY_ATLAS',			'POLICY_A_ATLAS'),
		('POLICY_QIN_BLANK',	        'TXT_KEY_POLICY_DYNASTY_BLANK_2',			    'TXT_KEY_POLICY_DYNASTY_BLANK_TEXT_2',	    'TXT_KEY_POLICY_DYNASTY_BLANK_HELP_2',			 1000,	 1000,		       47,		'POLICY_ATLAS',			'POLICY_A_ATLAS'),
		('POLICY_SUI_BLANK',	        'TXT_KEY_POLICY_DYNASTY_BLANK_3',			    'TXT_KEY_POLICY_DYNASTY_BLANK_TEXT_3',	    'TXT_KEY_POLICY_DYNASTY_BLANK_HELP_3',			 1000,	 1000,		       47,		'POLICY_ATLAS',			'POLICY_A_ATLAS'),
		('POLICY_TANG_BLANK',	        'TXT_KEY_POLICY_DYNASTY_BLANK_4',			    'TXT_KEY_POLICY_DYNASTY_BLANK_TEXT_4',	    'TXT_KEY_POLICY_DYNASTY_BLANK_HELP_4',			 1000,	 1000,		       47,		'POLICY_ATLAS',			'POLICY_A_ATLAS'),
		('POLICY_SONG_BLANK',	        'TXT_KEY_POLICY_DYNASTY_BLANK_5',			    'TXT_KEY_POLICY_DYNASTY_BLANK_TEXT_5',	    'TXT_KEY_POLICY_DYNASTY_BLANK_HELP_5',			 1000,	 1000,		       47,		'POLICY_ATLAS',			'POLICY_A_ATLAS'),
		('POLICY_YUAN_BLANK',	        'TXT_KEY_POLICY_DYNASTY_BLANK_6',			    'TXT_KEY_POLICY_DYNASTY_BLANK_TEXT_6',	    'TXT_KEY_POLICY_DYNASTY_BLANK_HELP_6',			 1000,	 1000,		       47,		'POLICY_ATLAS',			'POLICY_A_ATLAS'),
		('POLICY_MING_BLANK',	        'TXT_KEY_POLICY_DYNASTY_BLANK_7',			    'TXT_KEY_POLICY_DYNASTY_BLANK_TEXT_7',	    'TXT_KEY_POLICY_DYNASTY_BLANK_HELP_7',			 1000,	 1000,		       47,		'POLICY_ATLAS',			'POLICY_A_ATLAS');