--==========================================================================================================================
-- Cities
--==========================================================================================================================		
INSERT INTO Civilization_CityNames
			(CivilizationType, 				CityName)
VALUES		('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_PORT_AU_PRINCE'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_CAP_HAITIEN'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_GONAIVES'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_JACMEL'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_CARREFOUR'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_DELMAS'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_PETIONVILLE'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_SAINT_MARC'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_CITE_SOLEIL'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_CROIX_DES_BOUQUETS'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_PORT_DE_PAIX'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_LEOGANE'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_DESSALINES'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_PETIT_GOAVE'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_PETITE_RIVIER_DE_LARTIBONITE'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_GROS_MORN'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_LES_CAYES'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_SAINT_MICHEL_DE_LATALAYE'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_JEAN_RABEL'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_VERRETTES'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_GRAND_GOAVE'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_JEREMIE'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_ARCAHIE'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_TABARRE'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_HINCHE'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_SAINT_LOUIS_DU_NORD'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_OUANAMINTHE'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_AQUIN'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_MIREBALAIS'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_BAINET'),
			('CIVILIZATION_LEUGI_HAITI', 	'TXT_KEY_CITY_NAME_BELLADERE');

--==========================================================================================================================
--==========================================================================================================================		
